language: r
sudo: false
cache: packages

warnings_are_errors: true

r_github_packages:
  - statnet/EpiModelHPC
  - statnet/tergmLite/tergmLite

notifications:
  email:
    on_success: never
    on_failure: change
