# Syphilis ratio
boxplot(sim$epi$prev.syph.hivpos / sim$epi$prev.syph.hivneg)

# Syphilis prevalence plots
par(mfrow = c(2,2), oma = c(0,0,2,0))
plot(sim, y = "prev.syph.hivpos", ylab = "Prevalence", ylim = c(0, 0.15), col = "blue")
plot(sim, y = "prev.syph.hivneg", ylab = "Prevalence", add = TRUE, col = "green")
abline(h = 0.103, col = "red", lty = 2)
abline(h = 0.026, col = "red", lty = 2)
title("Syphilis by HIV Status")
plot(sim, y = "prev.stage.prim", ylab = "Prevalence", ylim = c(0.10, 0.20), col = "blue")
plot(sim, y = "prev.stage.seco", ylab = "Prevalence", add = TRUE, col = "green")
abline(h = 0.1385, col = "red", lty = 2)
abline(h = 0.1385, col = "red", lty = 2)
title("P and S Syphilis Prevalence")
plot(sim, y = "prev.stage.earlat", ylab = "Prevalence", ylim = c(0.15, 0.35), col = "blue")
plot(sim, y = "prev.stage.latelat", ylab = "Prevalence", add = TRUE, col = "green")
abline(h = 0.2770, col = "red", lty = 2)
abline(h = 0.20, col = "red", lty = 2)
title("Early and Late Latent Syphilis Prevalence")
plot(sim, y = "prev.stage.earlat", ylab = "Prevalence", ylim = c(0, 0.35), col = "blue")
plot(sim, y = "prev.stage.latelat", ylab = "Prevalence", add = TRUE, col = "green")
abline(h = 0.2770, col = "red", lty = 2)
abline(h = 0.046, col = "red", lty = 2)
title("Late Late Latent and Tertiary Syphilis Prevalence")


# STI Prevalence
par(mfrow = c(2,2), oma = c(0,0,2,0))
plot(sim, y = "prev.syph", ylab = "Prevalence")
title("Syphilis Prevalence")
abline(h = 0.046, col = "red", lty = 2)
plot(sim, y = "prev.ct", ylab = "Prevalence")
title("CT Prevalence")
plot(sim, y = "prev.gc", ylab = "Prevalence")
title("GC Prevalence")
plot(sim, y = "i.prev", ylab = "Prevalence")
abline(h = 0.26, col = "red", lty = 2)
title("HIV Prevalence")
#title("Syph Tprob = XXX, Syph.HIV.RR = , HIV.Syph.RR =", outer = TRUE)

# HIV and STI Incidence
par(mfrow = c(2,2), oma = c(0,0,2,0))
plot(sim, y = "ir100")
abline(h = 3.8, col = "red", lty = 2)
title("HIV Incidence")
plot(sim, y = "ir100.gc")
abline(h = 4.2, col = "red", lty = 2)
title("GC Incidence")
plot(sim, y = "ir100.ct")
abline(h = 6.6, col = "red", lty = 2)
title("CT Incidence")
plot(sim, y = "ir100.syph")
abline(h = 0.9, col = "red", lty = 2)
title("Syph Incidence")
#title("Syph Tprob = XXX, Relrisk for Syph<->HIV = XXX", outer = TRUE)
