// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aging_msm
List aging_msm(List dat, int at);
RcppExport SEXP EpiModelHIV_aging_msm(SEXP datSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type at(atSEXP);
    rcpp_result_gen = Rcpp::wrap(aging_msm(dat, at));
    return rcpp_result_gen;
END_RCPP
}
// aging_het
List aging_het(List dat, int at);
RcppExport SEXP EpiModelHIV_aging_het(SEXP datSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type at(atSEXP);
    rcpp_result_gen = Rcpp::wrap(aging_het(dat, at));
    return rcpp_result_gen;
END_RCPP
}
