// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// aging_msm
List aging_msm(List dat, int at);
RcppExport SEXP EpiModelHIV_aging_msm(SEXP datSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type at(atSEXP);
    __result = Rcpp::wrap(aging_msm(dat, at));
    return __result;
END_RCPP
}
// aging_het
List aging_het(List dat, int at);
RcppExport SEXP EpiModelHIV_aging_het(SEXP datSEXP, SEXP atSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type at(atSEXP);
    __result = Rcpp::wrap(aging_het(dat, at));
    return __result;
END_RCPP
}
