# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Aging Module
#'
#' @description Module for aging over time for nodes in the population.
#'
#' @param dat Master data list object of class \code{dat} containing networks,
#'        individual-level attributes, and summary statistics.
#' @param at Current time step.
#'
#' @return
#' This function returns \code{dat} after updating the nodal attribute
#' \code{age} and \code{sqrt.age}. The \code{sqrt.age} vertex attribute is also
#' updated on the three networks.
#'
#' @keywords module msm
#' @export
aging_msm <- function(dat, at) {
    .Call('EpiModelHIV_aging_msm', PACKAGE = 'EpiModelHIV', dat, at)
}

#' @title Aging Module
#'
#' @description This module ages all nodes in the population by one time
#'              unit at each time step.
#'
#' @param dat Master data list object of class \code{dat} containing networks,
#'        individual-level attributes, and summary statistics.
#' @param at Current time step.
#'
#' @keywords module het
#' @export
aging_het <- function(dat, at) {
    .Call('EpiModelHIV_aging_het', PACKAGE = 'EpiModelHIV', dat, at)
}

