# Synergy plots

par(mfrow=c(2,3), oma=c(2,2,2,2))
plot(sim, y = "prev.syph.hivpos", ylab = "Prevalence")
plot(sim, y = "prev.syph.hivneg", ylab = "Prevalence", add = TRUE)
title("Syphilis by HIV Status")
plot(sim, y = "prev.gc.hivpos", ylab = "Prevalence")
plot(sim, y = "prev.gc.hivneg", ylab = "Prevalence", add = TRUE)
title("GC by HIV Status")
plot(sim, y = "prev.ct.hivpos", ylab = "Prevalence")
plot(sim, y = "prev.ct.hivneg", ylab = "Prevalence", add = TRUE)
title("CT by HIV Status")
plot(sim, y = "prev.hiv.syphpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.syphneg", ylab = "Prevalence", add = TRUE)
title("HIV by Syphilis +/-")
plot(sim, y = "prev.hiv.gcpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.gcneg", ylab = "Prevalence", add = TRUE)
title("HIV by GC +/-")
plot(sim, y = "prev.hiv.ctpos", ylab = "Prevalence")
plot(sim, y = "prev.hiv.ctneg", ylab = "Prevalence", add = TRUE)
title("HIV by CT +/-")
title("Syph Tprob = 0.018, Relrisk for Syph<->HIV = 2.5", outer = TRUE)